query collection($handle: String!) {
  collection(handle: $handle) {
    id
    handle
    title
    description
    descriptionHtml
    products(first: 10) {
      nodes {
        id
        title
        handle
      }
    }
  }
}