// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokRichTextDoc, StoryblokMultilink, StoryblokMultiasset } from '../storyblok.d.ts';
export interface BlockButton {
  title: string;
  link: StoryblokMultilink;
  connecting_line?: boolean;
  component: "block_button";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockCard {
  title: string;
  headline: string;
  media_new?: StoryblokMultiasset;
  ratio: number | string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  column_start: number | string;
  column_end: number | string;
  connecting_line?: boolean;
  component: "block_card";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockCardEditorial {
  title: string;
  media: StoryblokAsset;
  ratio: number | string;
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  column_start: number | string;
  column_end: number | string;
  connecting_line?: boolean;
  component: "block_card_editorial";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockCarousel {
  items: Slide[];
  two_per_slide?: boolean;
  autoplay?: boolean;
  connecting_line?: boolean;
  component: "block_carousel";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockGallery {
  items: Slide[];
  connecting_line?: boolean;
  component: "block_gallery";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockMedia {
  media: StoryblokAsset;
  caption?: string;
  ratio: number | string;
  column_start: number | string;
  column_end: number | string;
  connecting_line?: boolean;
  component: "block_media";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockMenus {
  media?: StoryblokAsset;
  component: "block_menus";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockPlayer {
  media_url: string;
  autoplay?: boolean;
  component: "block_player";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockShopifyCollection {
  handle: string;
  component: "block_shopify_collection";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockSplit {
  media: StoryblokAsset;
  caption?: string;
  ratio: number | string;
  text: StoryblokRichTextDoc;
  reversed?: boolean;
  connecting_line?: boolean;
  component: "block_split";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockText {
  text: StoryblokRichTextDoc;
  connecting_line?: boolean;
  component: "block_text";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockTextColumns {
  title?: string;
  text: StoryblokRichTextDoc;
  connecting_line?: boolean;
  component: "block_text_columns";
  _uid: string;
  _editable?: string | undefined;
}

export interface ImageVideo {
  media: StoryblokAsset;
  component: "image_video";
  _uid: string;
  _editable?: string | undefined;
}

export interface Link {
  title: string;
  link: StoryblokMultilink;
  component: "link";
  _uid: string;
  _editable?: string | undefined;
}

export interface LinkGroup {
  title: string;
  hidden_on_mobile?: boolean;
  links: Link[];
  component: "link_group";
  _uid: string;
  _editable?: string | undefined;
}

export interface LinkList {
  items: Link[];
  component: "link_list";
  _uid: string;
  _editable?: string | undefined;
}

export interface Menu {
  title: string;
  pdf: StoryblokAsset;
  component: "menu";
  _uid: string;
  _editable?: string | undefined;
}

export interface Page {
  seo: Seo[];
  cover_message?: string;
  themes?: Theme[];
  blocks?: (
    | BlockButton
    | BlockCard
    | BlockCardEditorial
    | BlockCarousel
    | BlockGallery
    | BlockMedia
    | BlockMenus
    | BlockPlayer
    | BlockShopifyCollection
    | BlockSplit
    | BlockText
    | BlockTextColumns
  )[];
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface Seo {
  title: string;
  description: string;
  image: StoryblokAsset;
  component: "seo";
  _uid: string;
  _editable?: string | undefined;
}

export interface Settings {
  cover_message?: string;
  navigation_new?: (Link | LinkGroup)[];
  opening_times_title?: string;
  opening_times?: StoryblokRichTextDoc;
  contact_title?: string;
  contact?: StoryblokRichTextDoc;
  reservations_title?: string;
  reservations?: StoryblokRichTextDoc;
  newsletter_title?: string;
  newsletter?: StoryblokRichTextDoc;
  footer?: LinkList[];
  social_facebook?: string;
  social_tiktok?: string;
  social_instagram?: string;
  social_vimeo?: string;
  component: "settings";
  _uid: string;
  _editable?: string | undefined;
}

export interface Slide {
  media: StoryblokAsset;
  caption?: string;
  component: "slide";
  _uid: string;
  _editable?: string | undefined;
}

export interface Theme {
  background: "white" | "offwhite" | "mint" | "green" | "olive" | "brown";
  text: "white" | "green";
  component: "theme";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = BlockSplit | Page | Settings;
